### ISSUE TITLE
set min-date,max-date then get bug(strange behavior)

### ISSUE THREAD

**Issue by kenta3578** [plusone-masaki/vue-drumroll-datetime-picker#16]
Thank you for your development.
I found some strange behavior when using this package.
I appreciate if you fix or advise me usage to fix it

## procedure to show strange behavior
1. clone the master branch, then run the commands yarn and yarn dev
2. set min-date '2021/12/09' , max-date="2022/01/07"  in src/demo/examples/BasicUsages.vue line 27 ~ 29.
3. when select "year select" app behavior is something wrong
![スクリーンショット 2021-11-09 11 51 20](https://user-images.githubusercontent.com/42378029/140853198-d00adc9f-6cc7-4153-ba15-5b5f41f084e1.png)

https://user-images.githubusercontent.com/42378029/140851003-f07139e1-29c6-494f-b754-ed2c2a30bbb6.mov

**Comment by kenta3578** [comment]
I found another bug(strange behavior).
When set min-date '2022/01/09', max-date="2022/02/08",
and select "year select", then window is freeze.

**Comment by plusone-masaki** [comment]
Thank you for reporting the issue. 
This is a deeper problem than I expected, and it would be difficult to fix it unless I was the developer.
We are currently working on a fix, so please wait for a while.

**Comment by plusone-masaki** [comment]
This issue has been fixed in v0.3.1 released the other day.
The package now has the scope `@ plusone-masaki` and will need to be reinstalled.
Please refer to the following for the installation method.

https://github.com/plusone-masaki/vue-drumroll-datetime-picker/packages/1092715
