### ISSUE TITLE
unable to install css

### ISSUE THREAD

**Issue by BEIIKS** [plusone-masaki/vue-drumroll-datetime-picker#27]
when I try to import css vue-drumroll-datetime-picker css its says: 
`vue-drumroll-datetime-picker/vue-drumroll-datetime-picker.css in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./nod
e_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&`

To install it, you can run: npm install --save vue-drumroll-datetime-picker/vue-drumroll-datetime-picker.css
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'`

and when I try to install its ask to get a personal token or authenticate with github...

**Comment by plusone-masaki** [comment]
I'm sorry, the README was out of date. Please try this.

```
import 'vue-drumroll-datetime-picker/style.css'
```
