### ISSUE TITLE
Having an issue compiling a vue project with this module.

### ISSUE THREAD

**Issue by torrinworx** [plusone-masaki/vue-drumroll-datetime-picker#35]
![image](https://user-images.githubusercontent.com/82110564/195237018-81b05125-170d-4e76-8c5a-229d508110ec.png)

I keep getting the above error when I run `npm run dev`. What could I be doing wrong? 

I don't use Vue.js that often, is there any way to get just the JS, CSS, and HTML for the datetime picker? I really like the functionality and want to tinker with it. Really appreciate any help!

**Comment by plusone-masaki** [comment]
Thank you for using it.
See the same issue posted here.
https://github.com/plusone-masaki/vue-drumroll-datetime-picker/issues/27
