### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by donilearn** [plusone-masaki/vue-drumroll-datetime-picker#39]
I'm tring to install via npm, but I see some errors like: 

npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm -v 
- 9.4.0

node -v
- 18.12.1

**Comment by plusone-masaki** [comment]
Try installing Git.
https://git-scm.com/
