### ISSUE TITLE
Broken on vue3 ?

### ISSUE THREAD

**Issue by grojguy** [plusone-masaki/vue-drumroll-datetime-picker#40]
Thank you so much for this excellent module!  

I updated my project to Vue3, and I now I have many errors from DateTimePicker, and the application is no longer working.

Is vue-drumroll-datetime-picker not working with Vue3? 

Thank you!

![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/3d1da705-1840-4b22-8114-44f0ad29f657)

**Comment by plusone-masaki** [comment]
Yes, we have not yet published support for Vue3.
The development is already almost complete, so could you please try this branch?

https://github.com/plusone-masaki/vue-drumroll-datetime-picker/tree/feature/vue3_support

**Comment by grojguy** [comment]
Thank you!  Yes, I will give it a try.  However, I apologize... I do not know how to manually install in my vue.js project.  Where would I find instructions how to manually install?

> Yes, we have not yet published support for Vue3. The development is already almost complete, so could you please try this branch?
> 
> https://github.com/plusone-masaki/vue-drumroll-datetime-picker/tree/feature/vue3_support

**Comment by plusone-masaki** [comment]
Try this command.

`yarn add https://github.com/plusone-masaki/vue-drumroll-datetime-picker.git#feature/vue3_support`

**Comment by grojguy** [comment]
> Try this command.
> 
> `yarn add https://github.com/plusone-masaki/vue-drumroll-datetime-picker.git#feature/vue3_support`

Thank you!  I have installed the feature/vue3_support branch.  

However, I have the following error...
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/a46dd8d6-7078-4bda-9bc9-8e411db2b67a)

I have created a devbox demo using a basic Vue3 project:  [codesandbox.io](https://codesandbox.io/p/devbox/vue-drumroll-datetime-picker-vue3-demo-dp8qlp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrf9rjuy00072a6879xsg13e%2522%252C%2522sizes%2522%253A%255B73.10302031224519%252C26.896979687754808%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrf9rjuy00022a6841nf8udb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrf9rjuy00042a685mdavx93%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrf9rjuy00062a68dhzj8kao%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrf9rjuy00022a6841nf8udb%2522%253A%257B%2522id%2522%253A%2522clrf9rjuy00022a6841nf8udb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrf9rjuy00012a68gyucqph6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftemp%252Fvue-drumroll-datetime-picker%252Fvite.config.js%2522%252C%2522id%2522%253A%2522clrfm33by02ku2a68r1ds417z%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrfmsoxn00022a68drycskin%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrf9rjuy00012a68gyucqph6%2522%257D%252C%2522clrf9rjuy00062a68dhzj8kao%2522%253A%257B%2522id%2522%253A%2522clrf9rjuy00062a68dhzj8kao%2522%252C%2522activeTabId%2522%253A%2522clrfo92rk01m12a68ni7a2qmr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clrfo92rk01m12a68ni7a2qmr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrf9rjuy00042a685mdavx93%2522%253A%257B%2522id%2522%253A%2522clrf9rjuy00042a685mdavx93%2522%252C%2522activeTabId%2522%253A%2522clrf9rjuy00032a68ypyven0o%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrf9rjuy00032a68ypyven0o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clrfnrgud01192a68lvs7z0bc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrfo7zgy000deehv9gwr0uqw%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
(NOTE: The [feature/vue3_support](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/tree/feature/vue3_support) branch is cloned locally in this devbox, and installed to the project from this cloned repo, because the direct repo reference does not seem to work in codebase.io (hangs forever during 'npm install').  However, I don't think this is relevant to the error because in my real dev environment, I use the direct link to the git repo link you suggested above, and I see the same error shown above.)

The likely problem... after installing directly from the repo, or from the local clone, in **node_modules** there is no **src** or **dist** folder ...
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/ee50337d-0195-4f16-88db-c255a6b85b22)

However, if I install normally the release version (`npm install vue-drumroll-datetime-picker`), I see the expected contents...
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/3df3afa9-b765-4a64-981e-b51e50650f29)


Thank you for any assistance.

**Comment by plusone-masaki** [comment]
Thank you for your verification.
It may not be possible to install correctly unless you publish to npm.
i will try. thank you.

**Comment by plusone-masaki** [comment]
I just published it.
Try out v2.0.0 by running this command.

`npm i vue-drumroll-datetime-picker`

**Comment by grojguy** [comment]
> I just published it. Try out v2.0.0 by running this command.
> 
> `npm i vue-drumroll-datetime-picker`

Thank you!  OK, I was able to installa and run.  However, (2) issues...

1. According to your README...
```
<script>
import { DateTimePicker, DatePicker, TimePicker } from 'vue-drumroll-datetime-picker'
import 'vue-drumroll-datetime-picker/style.css'
//...
</script>
```
However, that appears to be wrong path for `style.css`.  
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/01d2ffb1-5fc5-4ff0-b9ff-89795038e7cd)
It is at `vue-drumroll-datetime-picker/dist/style.css'`, so I had to change the import line to...
`import 'vue-drumroll-datetime-picker/style.css'`

2. Something has changed with styling. With Vue2 and version vue-drumroll-datetime-picker@1.x.x and the following code...
```
             <div class="flex" style="width: 50%; font-size: 1.9em; align-items: center; justify-content: left;">
                <date-time-picker style="width: 100%; color: black;"
                  v-model="date.cur.fmtd"
                  height="5.5em"
                  :format="curDateFormatMask"
                  :pattern="{
                  }"
                  @input="saveUpdate"
                />
              </div>
```
... I had this...
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/ce429338-c038-44eb-baae-e0d6c6811ac5)

But with Vue3 and vue-drumroll-datetime-picker@2.0.0, I have this...
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/b34cd0ed-1ba5-4408-97e0-5be16057a348)

It appears to be a font size issue, but I cannot change font size, e.g...
```
                <date-time-picker style="width: 100%; color: black; font-size: 2em;"
                  v-model="date.cur.fmtd"
                  height="5.5em"
                  :format="curDateFormatMask"
                  :pattern="{
                  }"
                  @input="saveUpdate"
                />
```
... has no effect.

Any thoughts?

**Comment by plusone-masaki** [comment]
Thank you for the report. I will fix the stylesheet path in the README.
The display problem may also be due to two implementation issues.

1. Try specifying the font size for the parent element such as a div.
2. The library used internally for scrolling calculates the height, so if the parent element is smaller than necessary or hidden with `display: none` etc. before displaying the Picker, the height may be high. The calculation of the value may be incorrect.
     In this case, I think it will return to normal by resetting the value set in `v-model` to another value. Please try it.

**Comment by grojguy** [comment]
I have simplified the code, and tried both suggestions, and both seem to make no difference, as seen below...

Here is the excerpt of simplified code...
```
              <div class="flex q-pr-lg" style="font-size: 1.5em; width: 25%; align-items: center; justify-content: right;">
                Date/{{ $t("AH_TIME_STR") }}:
              </div>
              <div class="flex" style="width: 50%;">
                <date-time-picker style="width: 100%; color: black;"
                  modelValue="2024-01-31 12:26"
                />
              </div>
              <div class="flex q-pl-sm" style="width: 15%; font-size: 2.5em; align-items: center; justify-content: left;">
                <KeyboardInput />
              </div>
```
This gives: 
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/171923b1-5326-4b33-a757-067d8cb15915)

If I then change the middle `<div>`, adding `font-size: 2em;` to style, there is no change...
```
              <div class="flex" style="width: 50%; font-size: 2em;">
                <date-time-picker style="width: 100%; color: black;"
                  modelValue="2024-01-31 12:26"
                />
              </div>
```
![image](https://github.com/plusone-masaki/vue-drumroll-datetime-picker/assets/3414035/e60f2cf1-ca86-417a-a7a8-506216bb0d56)

Overall, it looks like there are problems both with scaling, and positioning of the characters and containers. 

Thank you for your help. Let me know if I can provide anything more to help with troubleshooting. I look forward to getting this working again.

**Comment by plusone-masaki** [comment]
@grojguy 
I don't know if it will solve the problem, but first try pasting the code in the [demo](https://www.plus-one.tech/vue-drumroll-datetime-picker/) as is and see if it works.
Then, by customizing it, you can explore the possibility of achieving what you want.

Mark this thread as resolved.
